### PR TITLE
Use CSS cascade rather than duplicating code

### PR DESCRIPTION
**Pull request by ghost**
Use CSS cascade behavior rather than duplicating code in order to lighten generated CSS

### CODE REVIEW

**Comment by jsomsanith-tlnd** [comment]
Squashed and merged on master.
Just a little error fix on button-wave.
Thank you f4bien

**Comment by ghost** [comment]
Jimmy, did you know that [Github](https://github.com/blog/2141-squash-your-commits) did the stuff?

**Comment by jsomsanith-tlnd** [comment]
Didn't know that. I changed the settings to only allow quash merge.
Thanks for the info :)

**Comment by francisu** [comment]
Hey thanks for this Fabien, I did not know this was possible.

On Fri, Apr 8, 2016 at 1:11 AM, Fabien Rassinier notifications@github.com
wrote:

> Jimmy, did you know that Github
> https://github.com/blog/2141-squash-your-commits did the stuff?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Talend/sunchoke/pull/1#issuecomment-207298834

## 

Cell +1 510 432 1589 (when in US)
Cell +33 7 83 72 48 66 (when in Europe)

**Pull request closed without merging**
